#! /bin/bash

CMLOGPATH=~/clog/chmodded.log

if [[ $1 == -r ]]; then
	chmod 444 $2
	echo $2 "now set to read-only"
	echo "">> $CMLOGPATH
	echo $2 "File permissions changed: ">> $CMLOGPATH
	ls -l $2 >> $CMLOGPATH
elif [[ $1 == -w ]]; then
	chmod 222 $2
	echo $2 "set to write-only"
	echo "">>$CMLOGPATH
        echo $2 "File permissions changed: ">> $CMLOGPATH
        ls -l $2 >> $CMLOGPATH
elif [[ $1 == -x ]]; then
        chmod 111 $2
        echo $2 "set to execute-only"
        echo "">>$CMLOGPATH
        echo $2 "File permissions changed: ">>$CMLOGPATH
        ls -l $2 >> $CMLOGPATH
elif [[ $1 == -r+ ]]; then
        chmod 666 $2
        echo $2 "set to read-write"
        echo "">>$CMLOGPATH
        echo $2 "File permissions changed: ">>$CMLOGPATH
        ls -l $2 >> $CMLOGPATH
elif [[ $1 == -w+ ]]; then
        chmod 333 $2
        echo $2 "set to write-execute"
        echo "">>$CMLOGPATH
        echo $2 "File permissions changed: ">>$CMLOGPATH
        ls -l $2 >> $CMLOGPATH
elif [[ $1 == -x+ ]]; then
        chmod 555 $2
        echo $2 "set to read-execute"
        echo "">>$CMLOGPATH
        echo $2 "File permissions changed: ">>$CMLOGPATH
        ls -l $2 >> $CMLOGPATH
elif [[ $1 == -a ]]; then
        chmod 222 $2
        echo "All permisions granted to all users for" $2
        echo "">>$CMLOGPATH
        echo $2 "File permissions changed: ">>$CMLOGPATH
        ls -l $2 >> $CMLOGPATH
elif [[ $1 == 1 ]]; then
	echo "Modify user permission mode"
	if [[ $2 == -r ]]; then
	        chmod u+r $3
                echo $3 "Set to read-only"
	        echo "">>$CMLOGPATH
	        echo $3 "File permissions changed: ">>$CMLOGPATH
        	ls -l $3 >> $CMLOGPATH
	elif [[ $2 == -w ]]; then
        	chmod u+w $3
        	echo $3 "set to write-only"
        	echo "">>$CMLOGPATH
        	echo $3 "File permissions changed: ">>$CMLOGPATH
        	ls -l $3 >> $CMLOGPATH
	elif [[ $3 == -x ]]; then
        	chmod u+x $3
        	echo $3 "set to execute-only"
        	echo "">>$CMLOGPATH
        	echo $3 "File permissions changed: ">>$CMLOGPATH
        	ls -l $3 >> $CMLOGPATH
	elif [[ $2 == -r+ ]]; then
        	chmod u+rw $3
        	echo $3 "set to read-write"
        	echo "">>$CMLOGPATH
        	echo $3 "File permissions changed: ">>$CMLOGPATH
        	ls -l $3 >> $CMLOGPATH
	elif [[ $2 == -w+ ]]; then
        	chmod u+wx $3
        	echo $3 "set to write-execute"
        	echo "">>$CMLOGPATH
        	echo $3 "File permissions changed: ">>$CMLOGPATH
        	ls -l $3 >> $CMLOGPATH
	elif [[ $2 == -x+ ]]; then
        	chmod u+rx $3
        	echo $3 "set to read-execute"
        	echo "">>$CMLOGPATH
        	echo $3 "File permissions changed: ">>$CMLOGPATH
        	ls -l $3 >> $CMLOGPATH
	elif [[ $2 == -a ]]; then
        	chmod u+rwx $3
        	echo "All permisions granted for" $2
        	echo "">>$CMLOGPATH
        	echo $3 "File permissions changed: ">>$CMLOGPATH
        	ls -l $3 >> $CMLOGPATH
        fi
        
elif [[ $1 == 2 ]]; then
        echo "Modify group permission mode"
        if [[ $2 == -r ]]; then
                chmod g+r $3
                echo "">>$CMLOGPATH
                echo $3 "File permissions changed: ">>$CMLOGPATH
                ls -l $3 >> $CMLOGPATH
        elif [[ $2 == -w ]]; then
                chmod g+w $3
                echo $3 "set to write-only"
                echo "">>$CMLOGPATH
                echo $3 "File permissions changed: ">>$CMLOGPATH
                ls -l $3 >> $CMLOGPATH
        elif [[ $3 == -x ]]; then
                chmod g+x $3
                echo $3 "set to execute-only"
                echo "">>$CMLOGPATH
                echo $3 "File permissions changed: ">>$CMLOGPATH
                ls -l $3 >> $CMLOGPATH
        elif [[ $2 == -r+ ]]; then
                chmod g+rw $3
                echo $3 "set to read-write"
                echo "">>$CMLOGPATH
                echo $3 "File permissions changed: ">>$CMLOGPATH
                ls -l $3 >> $CMLOGPATH
        elif [[ $2 == -w+ ]]; then
                chmod g+wx $3
                echo $3 "set to write-execute"
                echo "">>$CMLOGPATH
                echo $3 "File permissions changed: ">>$CMLOGPATH
                ls -l $3 >> $CMLOGPATH
        elif [[ $2 == -x+ ]]; then
                chmod g+rx $3
                echo $3 "set to read-execute"
                echo "">>$CMLOGPATH
                echo $3 "File permissions changed: ">>$CMLOGPATH
                ls -l $3 >> $CMLOGPATH
        elif [[ $2 == -a ]]; then
                chmod g+rwx $3
                echo "All permisions granted for" $2
                echo "">>$CMLOGPATH
                echo $3 "File permissions changed: ">>$CMLOGPATH
                ls -l $3 >> $CMLOGPATH
        fi
elif [[ $1 == 3 ]]; then
        echo "Modify others permission mode"
        if [[ $2 == -r ]]; then
                chmod o+r $3
                echo "">>$CMLOGPATH
                echo $3 "File permissions changed: ">>$CMLOGPATH
                ls -l $3 >> $CMLOGPATH
        elif [[ $2 == -w ]]; then
                chmod o+w $3
                echo $3 "set to write-only"
                echo "">>$CMLOGPATH
                echo $3 "File permissions changed: ">>$CMLOGPATH
                ls -l $3 >> $CMLOGPATH
        elif [[ $3 == -x ]]; then
                chmod o+x $3
                echo $3 "set to execute-only"
                echo "">>$CMLOGPATH
                echo $3 "File permissions changed: ">>$CMLOGPATH
                ls -l $3 >> $CMLOGPATH
        elif [[ $2 == -r+ ]]; then
                chmod o+rw $3
                echo $3 "set to read-write"
                echo "">>$CMLOGPATH
                echo $3 "File permissions changed: ">>$CMLOGPATH
                ls -l $3 >> $CMLOGPATH
        elif [[ $2 == -w+ ]]; then
                chmod o+wx $3
                echo $3 "set to write-execute"
                echo "">>$CMLOGPATH
                echo $3 "File permissions changed: ">>$CMLOGPATH
                ls -l $3 >> $CMLOGPATH
        elif [[ $2 == -x+ ]]; then
                chmod o+rx $3
                echo $3 "set to read-execute"
                echo "">>$CMLOGPATH
                echo $3 "File permissions changed: ">>$CMLOGPATH
                ls -l $3 >> $CMLOGPATH
        elif [[ $2 == -a ]]; then
                chmod o+rwx $3
                echo "All permisions granted for" $2
                echo "">>$CMLOGPATH
                echo $3 "File permissions changed: ">>$CMLOGPATH
                ls -l $3 >> $CMLOGPATH
        fi
else
	echo "WARNING, ONLY USING THE FLAG WILL APPLY THE PERMISSIONS TO ALL USERS
SET 1, 2, OR 3, BEFORE THE FLAG TO SPECIFY USER (1), GROUP (2), OR OTHERS (3)

	-r read-only
	-w write-only
	-x execute-only
	-r+ read-write
	-w+ write-execute
	-x+ read-execute
	-a read, write, and execute permissions
USES:
	chmodded -w filename > grants write-only permissions to all users
	chmodded -x+ filename > grants read-execute permissions to all users
	chmodded -a filename > grants all permissions to all users
	chmodded 1 -r filename > grants read-only permissions to the owner
	chmodded 3 -w+ filename > grants write-execute permissions to other users
	chmodded 2 -a filename > grants all permissions to all users"
fi
